interface EventsMap {
	NewConnection: []
	ConfigsChanged: []
	PanoramaFrame: []
	PanoramaWindowCreate: [windowName: string]
	PanoramaWindowDestroy: [windowName: string]
	ScriptsUpdated: []
	SetLanguage: [language: MenuLanguageID]
	KeyDown: [keyMask: VKeys]
	KeyUp: [keyMask: VKeys]
	CharInput: [char: string]
	MouseKeyDown: [key: VMouseKeys]
	MouseKeyUp: [key: VMouseKeys]
	MouseMove: []
	MouseWheel: [up: boolean]
}

interface NativeEventsMap {
	ConfigsChanged: []
	PanoramaFrame: []
	PanoramaWindowCreate: [windowName: string]
	PanoramaWindowDestroy: [windowName: string]
	CustomGameEvent: [eventName: string, data: RecursiveMap]
	DebuggerPrepareUnitOrders: [isUserInput: boolean, wasCancelled: boolean]
	Draw: [visualData: ArrayBuffer, w: number, h: number, x?: number, y?: number]
	GCPingResponse: []
	GameEvent: [eventName: string, obj: unknown]
	InputCaptured: [isCaptured: boolean]
	NewConnection: []
	PrepareUnitOrders: []
	ScriptsUpdated: []
	ServerMessage: [msgID: number, buf: ArrayBuffer]
	SetLanguage: [language: MenuLanguageID]
	SharedObjectChanged: [typeID: number, reason: number, msg: ArrayBuffer]
	WndProc: [messageType: number, wParam: bigint, lParam: bigint, x?: number, y?: number]
}
