// AUTO-GENERATED - do not edit.
declare namespace MenuSDK {
	const Classes: {
		readonly Row: "oct-row"
		readonly Pill: "oct-pill"
		readonly NavLabel: "oct-nav-label"
		readonly Switch: "oct-switch"
		readonly Knob: "oct-knob"
		readonly Chip: "oct-chip"
		readonly ButtonRow: "oct-button-row"
		readonly ButtonPrimary: "oct-button-primary"
		readonly ButtonSecondary: "oct-button-secondary"
		readonly ButtonGhost: "oct-button-ghost"
		readonly ButtonDanger: "oct-button-danger"
		readonly ButtonIcon: "oct-button-icon"
		readonly Control: "oct-control"
		readonly Ghost: "oct-ghost"
		readonly Primary: "oct-primary"
		readonly Close: "oct-close"
		readonly CloseIcon: "oct-close-icon"
		readonly MenuRow: "oct-menu-row"
		readonly MenuIcon: "oct-menu-icon"
		readonly Option: "oct-option"
		readonly Danger: "oct-danger"
		readonly DangerIcon: "oct-danger-icon"
		readonly Reset: "oct-reset"
		readonly Trigger: "oct-trigger"
		readonly Item: "oct-item"
		readonly PickerChip: "oct-picker-chip"
		readonly PickerChipIcon: "oct-picker-chip-icon"
		readonly PickerInput: "oct-picker-input"
		readonly PickerAdd: "oct-picker-add"
		readonly PickerAddIcon: "oct-picker-add-icon"
		readonly Keybind: "oct-keybind"
		readonly Search: "oct-search"
		readonly SearchLabel: "oct-search-label"
		readonly ControlIcon: "oct-control-icon"
		readonly DimIcon: "oct-dim-icon"
		readonly LiftIcon: "oct-lift-icon"
		readonly ModeIcon: "oct-mode-icon"
		readonly Swap: "oct-swap"
		readonly SwapOff: "oct-swap-off"
		readonly SwapOn: "oct-swap-on"
		readonly On: "oct-on"
	}
	function ClassOn(base: string, on: boolean): string
	function SheetActive(): boolean
	function SyncStyleSheet(): void
}
